/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoInputUnocss: typeof import('./src/components/autoInputUnocss/index.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CompoentsPage: typeof import('./src/components/compoentsPage/index.vue')['default']
    ComponentList: typeof import('./src/components/componentList/index.vue')['default']
    Content: typeof import('./src/components/content/index.vue')['default']
    DataBase: typeof import('./src/components/dataBase/index.vue')['default']
    GeneratedComponent: typeof import('./src/components/GeneratedComponent.vue')['default']
    GetComponent: typeof import('./src/components/getComponent/index.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LayersTree: typeof import('./src/components/layersTree/index.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NpmShow: typeof import('./src/components/npmShow/index.vue')['default']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NSelect: typeof import('naive-ui')['NSelect']
    NTab: typeof import('naive-ui')['NTab']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    RecursiveItem: typeof import('./src/components/layersTree/RecursiveItem.vue')['default']
    RenderContainer: typeof import('./src/components/content/RenderContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    StyleOptions: typeof import('./src/components/styleOptions/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    FocusTrap: typeof import('primevue/focustrap')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
